# Generated by Django 3.1.3 on 2020-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lon',
            field=models.FloatField(default=0),
        ),
    ]
